name: Stackbit Lighthouse CI
on:
  repository_dispatch:
    types: [stackbit-performance-check-trigger]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Audit URLs using Lighthouse
        id: LHCIAction
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            
            __STACKBIT_NETLIFY_SITENAME__/about.html
            __STACKBIT_NETLIFY_SITENAME__/blog/azimuth-improvements.html
            __STACKBIT_NETLIFY_SITENAME__/blog/customer-loyalty.html
            __STACKBIT_NETLIFY_SITENAME__/blog/customer-service-skills-that-every-employee-needs.html
            __STACKBIT_NETLIFY_SITENAME__/blog/design-azimuth.html
            __STACKBIT_NETLIFY_SITENAME__/blog/design-team-collaborates.html
            __STACKBIT_NETLIFY_SITENAME__/blog/index.html
            __STACKBIT_NETLIFY_SITENAME__/blog/sales-as-service.html
            __STACKBIT_NETLIFY_SITENAME__/blog/set-big-goals.html
            __STACKBIT_NETLIFY_SITENAME__/blog/user-journey-mapping.html
            __STACKBIT_NETLIFY_SITENAME__/blog/working-from-home.html
            __STACKBIT_NETLIFY_SITENAME__/contact.html
            __STACKBIT_NETLIFY_SITENAME__/features.html
            __STACKBIT_NETLIFY_SITENAME__/index.html
            __STACKBIT_NETLIFY_SITENAME__/pricing.html
            __STACKBIT_NETLIFY_SITENAME__/signup.html
            __STACKBIT_NETLIFY_SITENAME__/style-guide.html
            
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
      - name: Webhook
        uses: denar90/webhook-action@master
        env:
          webhookUrl: ${{secrets.STACKBIT_ACTION_WEBHOOK_URL}}
          data: '{ "gihub": ${{ toJSON(github) }}, "links": ${{steps.LHCIAction.outputs.links}} }'